import os
import traceback
import asyncio
from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from fastapi.responses import FileResponse
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Import project settings
from config import settings

# Import modules from new structure
from src.services.conversation.manager import ConversationManager
from src.services.ai.ai_service_manager import create_ai_service_manager
from src.services.safety.safety_guardrails import MedicalSafetyGuardrails
# RAG service for dynamic question generation
from src.services.ai.rag.chatbot import Chatbot

import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# --- Configuration Validation ---
# Validate the configuration on startup
settings.validate_configuration()

# --- Service Initialization ---
try:
    logger.info(f"Initializing services in '{settings.AI_SERVICE_MODE}' mode...")

    # 1. Initialize the AI Service Manager (handles MedGemma logic)
    # This is the primary interface for generating medical responses.
    ai_service_manager = create_ai_service_manager(settings.AI_SERVICE_MANAGER_CONFIG)
    logger.info(" AI Service Manager initialized.")

    # 2. Initialize the RAG service (for knowledge base lookups)
    # This is used for dynamic, context-aware question generation.
    rag_service = Chatbot(
        rag_config=settings.RAG_CONFIG,
        openai_api_key=settings.OPENAI_CONFIG["api_key"],
        ai_service=ai_service_manager  # Inject the AI service manager
    )
    logger.info(" RAG Service (Chatbot) initialized.")

    # 3. Initialize the Conversation Manager
    # This orchestrates the conversation flow, using the AI and RAG services.
    conversation_manager = ConversationManager(
        ai_service=ai_service_manager,
        rag_service=rag_service,
        safety_config=settings.SAFETY_CONFIG
    )
    logger.info(" Conversation Manager initialized.")

    # 4. Initialize Safety Guardrails
    safety_guardrails = MedicalSafetyGuardrails(settings.SAFETY_CONFIG)
    logger.info(" Medical Safety Guardrails initialized.")

    logger.info(" All services initialized successfully!")

except Exception as e:
    logger.critical(f" CRITICAL: Failed to initialize services. The application will not work correctly.")
    logger.critical(f"Error: {e}")
    # Print the full stack trace for detailed debugging
    traceback.print_exc()
    # Set services to None to prevent the app from starting in a broken state
    ai_service_manager = None
    rag_service = None
    conversation_manager = None
    safety_guardrails = None

app = FastAPI(
    title="AI Health Consultant API", 
    description="A secure medical AI assistant with MedGemma + RAG architecture", 
    version="3.0.0"
)

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.mount("/static", StaticFiles(directory="static"), name="static")

# Request models
class QueryRequest(BaseModel):
    query: str
    session_id: str
    is_choice: bool = False

class ImageAnalysisRequest(BaseModel):
    session_id: str
    image_data: str
    filename: str

@app.post("/chat")
async def chat(query_request: QueryRequest):
    """Enhanced chat endpoint with safety guardrails and MedGemma-RAG integration."""
    if not conversation_manager or not safety_guardrails:
        raise HTTPException(status_code=500, detail="Required services not initialized.")

    try:
        query_text = query_request.query.strip()
        session_id = query_request.session_id
        is_choice = query_request.is_choice

        logger.info(f" Session {session_id}: {query_text}")

        # Step 1: Safety check on user input
        safety_result = safety_guardrails.process_user_input(query_text)
        
        # Handle emergency situations
        if safety_result["should_block"]:
            logger.warning(f" Session {session_id}: Emergency situation detected")
            return {
                "response_type": "emergency",
                "response": safety_result["emergency_response"],
                "session_id": session_id
            }

        # Step 2: Process with conversation manager
        response = await conversation_manager.process_message(session_id, query_text, is_choice)
        
        # Step 3: Apply safety validation to the final diagnostic response
        # The ConversationManager is now responsible for generating the diagnosis.
        # This block is only for applying the final safety checks.
        if response.get('response_type') == 'diagnostic':
            try:
                # Retrieve the diagnosis that was already generated by the Conversation Manager
                original_diagnosis = response.get('diagnosis_description', '')
                
                # Apply safety validation to the AI response
                safety_validation = safety_guardrails.validate_response(original_diagnosis)
                
                if safety_validation["is_safe"]:
                    response['diagnosis_description'] = safety_validation["filtered_response"]
                    response['enhanced_with'] = 'MedGemma + RAG + Safety'
                    response['safety_validated'] = True
                    logger.info(f" Session {session_id}: Diagnostic response passed safety validation.")
                else:
                    logger.warning(f" Session {session_id}: AI response failed safety validation. Using fallback.")
                    # Overwrite the response with a clean, safe fallback
                    response['diagnosis_title'] = "Medical Consultation Recommended"
                    response['diagnosis_description'] = """Based on the information provided, it's recommended to consult with a healthcare professional for a proper evaluation. They can provide a personalized assessment and guide you on the best next steps."""
                    # Clear other fields to avoid mixing data
                    response.pop('final_explanation', None)
                    response['recommendations'] = ["Schedule an appointment with a primary care physician.", "Consider visiting an urgent care clinic if symptoms worsen."]
                    response['enhanced_with'] = 'Safety Fallback'
                    response['safety_validated'] = False
                
                # The 'final_explanation' field is no longer used, so we remove the redundant Phase 3 check.
                logger.info(f" Session {session_id}: Enhanced with {response.get('enhanced_with', 'N/A')}")
                
            except Exception as enhancement_error:
                logger.error(f" Safety validation on diagnostic response failed: {enhancement_error}")
                # Fallback to a generic safe response if validation itself fails
                response['diagnosis_title'] = "Medical Consultation Recommended"
                response['diagnosis_description'] = "I recommend consulting with a healthcare professional for a proper evaluation."
                response['enhanced_with'] = 'Default Safe Response'

        logger.info(f" Session {session_id}: Response sent successfully")
        return response

    except Exception as e:
        error_message = f" Internal Server Error: {str(e)}\n{traceback.format_exc()}"
        logger.error(error_message)
        raise HTTPException(status_code=500, detail="An internal error occurred.")

@app.post("/analyze_image")
async def analyze_image(
    session_id: str = Form(...), 
    image: UploadFile = File(...)
):
    """
    Analyzes a medical image, validates the analysis for safety, and integrates
    it into the conversation.
    """
    if not conversation_manager or not safety_guardrails or not ai_service_manager:
        logger.error("A required service is not initialized. Cannot process image.")
        raise HTTPException(status_code=500, detail="Core services not available.")

    try:
        logger.info(f"Session {session_id}: Received image for analysis: {image.filename}")

        # Read image data
        image_data = await image.read()

        # Use the AI Service Manager for image analysis
        analysis_result = await ai_service_manager.analyze_image(image_data, context="medical")
        service_used = analysis_result.get("service_used", "unknown")
        logger.info(f"Image analysis performed by: {service_used}")

        if not analysis_result.get("success"):
            error_msg = analysis_result.get('error', 'Unknown error during image analysis.')
            logger.error(f"Session {session_id}: Image analysis failed. Reason: {error_msg}")
            raise HTTPException(status_code=500, detail=f"Image analysis failed: {error_msg}")

        analysis_text = analysis_result["analysis"]
        
        # --- Safety Guardrails ---
        # 1. Check for immediate emergencies in the analysis text
        safety_check = safety_guardrails.process_user_input(analysis_text)
        if safety_check["should_block"]:
            logger.warning(f"Session {session_id}: Emergency detected in image analysis. Blocking response.")
            return {
                "response_type": "emergency",
                "response": safety_check["emergency_response"],
                "session_id": session_id
            }
        
        # 2. Validate and filter the AI-generated analysis for safety
        safety_validation = safety_guardrails.validate_response(analysis_text)
        final_analysis = safety_validation["filtered_response"]
        
        logger.info(f"Session {session_id}: Image analysis successful and safety-validated.")
        
        # Integrate the validated analysis into the conversation state
        response = conversation_manager.process_image_analysis(session_id, final_analysis)
        
        logger.info(f"Session {session_id}: Image analysis response sent to user.")
        return response

    except Exception as e:
        logger.critical(f"CRITICAL ERROR in /analyze_image: {e}", exc_info=True)
        # Provide a safe, generic error response
        try:
            return conversation_manager.process_image_analysis(
                session_id, 
                "I'm sorry, I encountered a problem while analyzing the image. Please describe your symptoms in text."
            )
        except Exception as fallback_e:
            logger.error(f"Fallback response in /analyze_image also failed: {fallback_e}")
            raise HTTPException(status_code=500, detail="An critical internal error occurred.")

@app.post("/transcribe")
async def transcribe_audio(session_id: str = Form(...), audio: UploadFile = File(...)):
    """
    Transcribes an audio file, validates the content for safety, and integrates
    it into the conversation.
    """
    if not conversation_manager or not safety_guardrails or not ai_service_manager:
        logger.error("A required service is not initialized. Cannot process audio.")
        raise HTTPException(status_code=500, detail="Core services not available.")

    try:
        logger.info(f"Session {session_id}: Received audio for transcription: {audio.filename}")

        audio_content = await audio.read()
        
        # Use the AI Service Manager for transcription
        transcription_result = await ai_service_manager.transcribe_audio(
            audio_content, 
            audio.filename or "audio.wav"
        )
        
        if not transcription_result["success"]:
            error_msg = transcription_result.get('error', 'Unknown error during transcription.')
            logger.error(f"Session {session_id}: Audio transcription failed. Reason: {error_msg}")
            # Still, we can process the partial or error message
            transcription_text = transcription_result.get("transcription", "")
        else:
            transcription_text = transcription_result["transcription"]

        # --- Safety Guardrails ---
        safety_check = safety_guardrails.process_user_input(transcription_text)
        if safety_check["should_block"]:
            logger.warning(f"Session {session_id}: Emergency detected in audio. Blocking response.")
            return {
                "response_type": "emergency", 
                "response": safety_check["emergency_response"],
                "session_id": session_id
            }
        
        logger.info(f"Session {session_id}: Audio transcribed and safety-validated.")
        
        # Integrate the transcription into the conversation
        response = conversation_manager.process_voice_transcription(session_id, transcription_text)
        
        logger.info(f"Session {session_id}: Audio transcription response sent.")
        return response

    except Exception as e:
        logger.critical(f"CRITICAL ERROR in /transcribe: {e}", exc_info=True)
        try:
            return conversation_manager.process_voice_transcription(
                session_id, 
                "I'm sorry, I couldn't process the audio. Please try typing your message."
            )
        except Exception as fallback_e:
            logger.error(f"Fallback response in /transcribe also failed: {fallback_e}")
            raise HTTPException(status_code=500, detail="An critical internal error occurred.")

@app.get("/health")
async def health_check():
    """Provides a detailed health check of all critical services."""
    
    # Base status
    status = {
        "api_status": "healthy",
        "configuration": settings.get_active_config(),
        "architecture": "MedGemma + RAG + Safety Guardrails"
    }

    # Service initialization status
    status["ai_service_manager_initialized"] = ai_service_manager is not None
    status["rag_service_initialized"] = rag_service is not None
    status["conversation_manager_initialized"] = conversation_manager is not None
    status["safety_guardrails_initialized"] = safety_guardrails is not None

    # Detailed status from AI Service Manager
    if ai_service_manager:
        service_status = ai_service_manager.get_service_status()
        status.update({
            "service_manager_details": service_status,
            "text_generation_available": service_status.get("text_generation_available", False),
            "image_analysis_available": service_status.get("image_analysis_available", False),
            "audio_transcription_available": service_status.get("audio_transcription_available", False)
        })
    
    # Detailed status from RAG Service
    if rag_service:
        status.update(rag_service.get_service_info())

    return status

@app.get("/safety-info")
async def get_safety_info():
    """Get information about safety guardrails."""
    if not safety_guardrails:
         raise HTTPException(status_code=503, detail="Safety guardrails are not initialized.")
    return safety_guardrails.get_safety_info()

@app.get("/")
async def read_index():
    return FileResponse('index.html')

@app.get("/mobile")
async def read_mobile():
    return FileResponse('mobile.html')

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)